http {
    include mime.types;
    server {
        listen 8080;
        root /home/matej/Projekti/draft-projects/static-content;

        location /fruits {
            root /home/matej/Projekti/draft-projects/static-content;
        }

        location /carbs {
            alias  /home/matej/Projekti/draft-projects/static-content/fruits;
        }

        location /vegetables {
            root /home/matej/Projekti/draft-projects/static-content;
            try_files /vegetables/veggies.html /index.html =404;
        }
    }


}

events {}
