AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  HelloWorldTable:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: Id
      Type: String
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1

  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      MemorySize: 128
      Timeout: 3
      CodeUri: app/
      Handler: main.handle_requests
      Runtime: python3.14
      Environment:
        Variables:
          TABLE_NAME: !ref HelloWorldTable
      Events:
        HelloWorld:
          Type: HttpApi  
          Properties:
            Path: /helloWorld 
            Method: GET

  MyConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: HelloWorldFunction
      Destination:
        Id: HelloWorldTable
      Permissions:
        - Read
        - Write

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      RouteSettings:
        "GET /pahelloWorldth":

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt
     HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn