AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Arhitectures: x86_64
      MemorySize: 128
      Timeout: 3
      CodeUri: app/
      Handler: main.handle_requests
      Runtime: python3.14
      Events:
        HelloWorld:
          Type: HttpApi  
          Properties:
            Path: /helloWorld 
            Method: GET

  HelloWorldTable:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: Id
      Type: String
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      RouteSettings:
        "GET /pahelloWorldth":

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt
     HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn