---
version: "3"

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./config:/config
    - prometheus-data:/prometheus
    restart: unless-stopped
    command:
    - "--config.file=/config/prometheus.yaml"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:13.0
    ports: 
    - "3000:3000"
    volumes:
    - grafana-data:/var/lib/grafana
    - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./provisioning/dashboards-json:/etc/grafana/provisioning/dashboards-json
    - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped


volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
