---
version: "3"

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./config:/config
    - prometheus-data:/prometheus
    restart: unless-stopped
    command:
    - "--config.file=/config/prometheus.yaml"
  grafana:
    image: grafana/grafana:13.0
    ports: 
    - "3000:3000"
    volumes:
    - grafana-data:/var/lib/grafana
    restart: unless-stopped


volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
