FROM apache/kafka:4.3.1
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_NUM_PARTITIONS=3
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 
ENTRYPOINT ["sh", "-c", "cd /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic test-topic"]
