
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-app
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKER: broker:9092
    depends_on:
      - broker
      - mongodb
  mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile-mongo
    ports:
      - "27017:27017"
  broker:
    build:
      context: .
      dockerfile: ./Dockerfile-kafka
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - kafka_kraft:/var/lib/kafka/data

volumes:
  kafka_kraft:

