FROM apache/kafka:4.3.1

ENTRYPOINT ["sh", "-c", "(until /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic images --if-not-exists 2>/dev/null; do sleep 2; done &) ; exec /etc/kafka/docker/run"]
