FROM apache/kafka:4.3.1
ENV      KAFKA_NODE_ID=1
ENV      KAFKA_PROCESS_ROLES=broker,controller
ENV      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV      KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
ENV      KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV      KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
ENV      KAFKA_AUTO_CREATE_TOPICS_ENABLE="false"
ENV      KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
CMD ["sh", "-c", "(until /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic images --if-not-exists 2>/dev/null; do sleep 2; done &) ; exec /etc/kafka/docker/run"]
