spring:
  application:
    name: expense-tracker
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_SCHEMA:mydatabase}
    username: ${APP_USERNAME:app_user}
    password: ${APP_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://dev-123456.oktapreview.com/oauth2/default/'
logging:
  level:
    org:
      springframework:
        security: DEBUG
rsa:
  private-key: 'classpath:certs/private.pem'
  public-key: 'classpath:certs/public.pem'
debug: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}