spring.application.name=expense-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.security=DEBUG

seed.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
seed.datasource.username=seed_user
seed.datasource.password=${SEED_DB_PASSWORD}