[project]
version = "2020.0.0"
name = "Broadcast"
dependencies = [
    "typer",
    "websockets",
    "typing-extensions"
]

[project.scripts]
greet = "pybroadcast.cli:app"

[project.entry-points."pipx.run"]
greet = "pybroadcast.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["pybroadcast*"]