[project]
version = "2020.0.0"
name = "Broadcast"
dependencies = [
    "typer",
    "websockets",
    "typing-extensions",
    "prompt-toolkit"
]

[project.scripts]
broadcast-server = "pybroadcast.cli:app"

[project.entry-points."pipx.run"]
broadcast-server = "pybroadcast.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["pybroadcast*"]